export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const GET_USERS = 'GET_USERS'
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const CLEAR_USERS = 'CLEAR_USERS'
export const ADD_FRIEND = 'ADD_FRIEND'
export const REMOVE_FRIEND = 'REMOVE_FRIEND'
export const GET_FRIENDS = 'GET_FRIENDS'